### ISSUE TITLE
Убрать ворнинги

### ISSUE THREAD

**Issue by AlecCross** [feya-bilyzna/feya-bilyzna.github.io#20]
Были замечены в процессе выполнения https://github.com/feya-bilyzna/feya-bilyzna.github.io/issues/17

[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by lifearoundfreaks** [comment]
Решилось билдом с другой машины.
