### ISSUE TITLE
Начинаем работу с отображением остатков и доступных вариантов товара

### ISSUE THREAD

**Issue by lifearoundfreaks** [feya-bilyzna/feya-bilyzna.github.io#22]
На данный момент мы уже можем получать базовую информацию о товарах с бекенда. А именно: информацию о цене во всех вариантах, а также о самих вариантах и количестве их в остатке. Необходимо использовать эту информацию и реализовать её отображение на странице товара, красивая реализация будет плюсом.

Не забываем, что на данный момент наши варианты товара хранят в себе лишь уникальное название и не содержат логики фильтрации / иконок / прочего.

Пример данных с бекенда:

![Untitled](https://user-images.githubusercontent.com/42870020/128606807-05128b79-9ebf-42b5-85fb-895b8db43ea5.png)

Добавлено: Так как мы решили делать фильтрацию с помощью нескольких селекторов, то можем также сделать логику для активации и деактивации кнопки "купить".

**Comment by AlecCross** [comment]
![image](https://user-images.githubusercontent.com/49411370/130029939-03b0456c-2e2f-47a3-82e5-046c518fdf90.png)
